# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b59b361753e1a87147d3f785e57ce9afebf0152e7a346fea42da08959fd826a606f77f77ab91f87a36546b365dbcdf07136875a88c1659cde709cd8692db71c

test:
  secret_key_base: 805196ca72f674f948f78198978743f76b27b48caeba278c701f28b863113e4988f9a7c7738a69b5e8f04c435636ada3d27d897f9cb4941587691c1016df8b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
